name: higher-environment-demo

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  uat:
    uses: akashkalleholkar/githubworkflows/.github/workflows/demo.yml@main

    with:
      #ENVIRONMENT: UAT
      BUILD: true
      TEST: true
      DEPLOY: true

    secrets:
      DEMO_TOKEN: ${{ secrets.DEMO_TOKEN }}
