name: Test MySQL Connection

on: 
  push:
    branches:
      - dev

jobs:
  test-mysql-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Test MySQL Connection
        run: |
          mysql -h 13.235.82.193 -P 3306 -u root -prootpass -e "SELECT 1; SHOW DATABASES;"
